<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LevelAndQuestionSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('questions')->truncate();
        DB::table('levels')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $now = now();
        $levels = [
            ['name' => 'Dasar Python', 'description' => 'Memahami dasar-dasar Python, syntax, dan cara menjalankan program', 'order_number' => 1, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Variabel & Tipe Data', 'description' => 'Belajar tentang variabel, tipe data int, float, str, bool, dan konversi tipe', 'order_number' => 2, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Operators', 'description' => 'Menggunakan operator aritmatika, perbandingan, logika, dan assignment', 'order_number' => 3, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Strings', 'description' => 'Bermain dengan string: indexing, slicing, method, dan formatting', 'order_number' => 4, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Lists', 'description' => 'Belajar struktur data list: membuat, mengakses, mengubah, dan method-methodnya', 'order_number' => 5, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Tuples & Sets', 'description' => 'Belajar Tuple (immutable) dan Set (unik, tidak berurutan)', 'order_number' => 6, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Dictionaries', 'description' => 'Belajar struktur data dictionary: key-value, method, dan nested dict', 'order_number' => 7, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Conditional Statements', 'description' => 'Percabangan if-elif-else, ternary operator, dan kondisi logika', 'order_number' => 8, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Loops', 'description' => 'Perulangan for dan while, range, break, continue, nested loop', 'order_number' => 9, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Functions', 'description' => 'Membuat dan menggunakan fungsi, parameter, return, scope, lambda', 'order_number' => 10, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now],
        ];

        foreach ($levels as $level) {
            DB::table('levels')->insert($level);
        }

        $level1Questions = [
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print("Hello, Python!")',
                'options' => json_encode(['Hello, Python!', 'Hello, World!', 'Error', 'python']),
                'correct_answer' => 'Hello, Python!',
                'explanation' => 'Fungsi print() menampilkan teks apa adanya ke layar.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk membuat komentar satu baris di Python?',
                'code_snippet' => null,
                'options' => json_encode(['# Ini komentar', '// Ini komentar', '<!-- Ini komentar -->', '-- Ini komentar']),
                'correct_answer' => '# Ini komentar',
                'explanation' => 'Python menggunakan tanda # untuk komentar satu baris.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah kode yang benar untuk menyapa user dengan input namanya?',
                'code_snippet' => null,
                'options' => json_encode([
                    'nama = input("Siapa nama kamu? ") print("Halo,", nama)',
                    'nama = scanf("Siapa nama kamu? ") print("Halo,", nama)',
                    'input(nama, "Siapa nama kamu? ") print("Halo", nama)',
                    'nama = read("Siapa nama kamu? ") print("Halo" + nama)'
                ]),
                'correct_answer' => 'nama = input("Siapa nama kamu? ") print("Halo,", nama)',
                'explanation' => 'input() digunakan untuk menerima masukan dari user, lalu hasilnya dicetak dengan print().',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Ekstensi file untuk program Python adalah...',
                'code_snippet' => null,
                'options' => json_encode(['.py', '.python', '.pyt', '.pt']),
                'correct_answer' => '.py',
                'explanation' => 'File Python menggunakan ekstensi .py',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'debugging',
                'answer_type' => 'mcq',
                'question_text' => 'Kode berikut error. Manakah perbaikan yang benar?',
                'code_snippet' => 'print "Belajar Python"',
                'options' => json_encode([
                    'print("Belajar Python")',
                    'Print "Belajar Python"',
                    'echo "Belajar Python"',
                    'printf "Belajar Python"'
                ]),
                'correct_answer' => 'print("Belajar Python")',
                'explanation' => 'Di Python 3, print adalah fungsi sehingga harus menggunakan tanda kurung.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print(2 + 3)',
                'options' => json_encode(['5', '23', '2 + 3', 'Error']),
                'correct_answer' => '5',
                'explanation' => 'Python menghitung operasi matematika 2 + 3 = 5, lalu mencetak hasilnya.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah pernyataan yang benar tentang Python?',
                'code_snippet' => null,
                'options' => json_encode([
                    'Python case-sensitive (nama != Nama)',
                    'Python tidak case-sensitive',
                    'Python menggunakan kurung kurawal untuk blok kode',
                    'Python membutuhkan titik koma di setiap baris'
                ]),
                'correct_answer' => 'Python case-sensitive (nama != Nama)',
                'explanation' => 'Python bersifat case-sensitive, artinya huruf besar dan kecil dibedakan.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Python dikembangkan oleh...',
                'code_snippet' => null,
                'options' => json_encode(['Guido van Rossum', 'James Gosling', 'Bjarne Stroustrup', 'Dennis Ritchie']),
                'correct_answer' => 'Guido van Rossum',
                'explanation' => 'Python diciptakan oleh Guido van Rossum pada tahun 1991.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'x = 10 print(x)',
                'options' => json_encode(['10', 'x', 'Error', 'None']),
                'correct_answer' => '10',
                'explanation' => 'Variabel x menyimpan nilai 10, lalu print(x) mencetak nilai dari variabel tersebut.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Indentasi yang dianjurkan di Python adalah...',
                'code_snippet' => null,
                'options' => json_encode(['4 spasi', '2 spasi', '1 tab', '8 spasi']),
                'correct_answer' => '4 spasi',
                'explanation' => 'Python menganjurkan indentasi 4 spasi untuk blok kode (PEP 8).',
                'test_cases' => null,
            ],
        ];

        $level2Questions = [
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara mendeklarasikan variabel di Python?',
                'code_snippet' => null,
                'options' => json_encode(['x = 5', 'var x = 5', 'int x = 5', 'let x = 5']),
                'correct_answer' => 'x = 5',
                'explanation' => 'Python tidak perlu keyword, cukup tulis nama_variabel = nilai.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa tipe data dari nilai 3.14?',
                'code_snippet' => 'x = 3.14 print(type(x))',
                'options' => json_encode(["<class 'float'>", "<class 'int'>", "<class 'str'>", "<class 'bool'>"]),
                'correct_answer' => "<class 'float'>",
                'explanation' => 'Angka desimal (dengan titik) bertipe float di Python.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print(type(True))',
                'options' => json_encode(["<class 'bool'>", "<class 'str'>", "<class 'int'>", 'True']),
                'correct_answer' => "<class 'bool'>",
                'explanation' => 'True dan False adalah tipe data boolean (bool) di Python.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah nama variabel yang TIDAK valid di Python?',
                'code_snippet' => null,
                'options' => json_encode(['2nama', 'nama2', '_nama', 'nama_saya']),
                'correct_answer' => '2nama',
                'explanation' => 'Nama variabel tidak boleh diawali dengan angka.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'x = "5" print(type(x))',
                'options' => json_encode(["<class 'str'>", "<class 'int'>", "<class 'float'>", '5']),
                'correct_answer' => "<class 'str'>",
                'explanation' => 'Nilai "5" diapit tanda kutip, sehingga bertipe string (str).',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah kode yang benar untuk mengubah string "123" menjadi integer?',
                'code_snippet' => null,
                'options' => json_encode(['int("123")', 'str(123)', 'integer("123")', '"123".toInt()']),
                'correct_answer' => 'int("123")',
                'explanation' => 'Gunakan int() untuk konversi string ke integer.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Tipe data untuk menyimpan nilai benar/salah adalah...',
                'code_snippet' => null,
                'options' => json_encode(['bool', 'int', 'str', 'float']),
                'correct_answer' => 'bool',
                'explanation' => 'Boolean (bool) digunakan untuk nilai True dan False.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'a = 10 b = 3 print(a + b)',
                'options' => json_encode(['13', '103', '10 + 3', 'Error']),
                'correct_answer' => '13',
                'explanation' => 'Variabel a dan b dijumlahkan: 10 + 3 = 13.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Nilai None di Python merepresentasikan...',
                'code_snippet' => null,
                'options' => json_encode(['Tidak ada nilai / kosong', 'Angka 0', 'False', 'String kosong']),
                'correct_answer' => 'Tidak ada nilai / kosong',
                'explanation' => 'None adalah tipe data khusus yang berarti tidak ada nilai (null).',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk membuat variabel dengan nilai float?',
                'code_snippet' => null,
                'options' => json_encode(['tinggi = 1.75', 'tinggi = "1.75"', 'tinggi = 1,75', 'float tinggi = 1.75']),
                'correct_answer' => 'tinggi = 1.75',
                'explanation' => 'Cukup tulis angka desimal dengan titik, Python otomatis mengenali sebagai float.',
                'test_cases' => null,
            ],
        ];

        $level3Questions = [
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi berikut?',
                'code_snippet' => 'print(10 // 3)',
                'options' => json_encode(['3', '3.33', '4', '1']),
                'correct_answer' => '3',
                'explanation' => 'Operator // adalah floor division (pembagian bulat ke bawah). 10 // 3 = 3.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi berikut?',
                'code_snippet' => 'print(10 % 3)',
                'options' => json_encode(['1', '3', '0', '3.33']),
                'correct_answer' => '1',
                'explanation' => 'Operator % adalah modulus (sisa bagi). 10 dibagi 3 sisa 1.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi berikut?',
                'code_snippet' => 'print(2 ** 4)',
                'options' => json_encode(['16', '8', '6', '2']),
                'correct_answer' => '16',
                'explanation' => 'Operator ** adalah pangkat. 2 ** 4 = 2 x 2 x 2 x 2 = 16.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi perbandingan berikut?',
                'code_snippet' => 'print(5 > 3)',
                'options' => json_encode(['True', 'False', '5', '3']),
                'correct_answer' => 'True',
                'explanation' => '5 lebih besar dari 3, sehingga hasilnya True.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi logika berikut?',
                'code_snippet' => 'print(True and False)',
                'options' => json_encode(['False', 'True', 'Error', 'None']),
                'correct_answer' => 'False',
                'explanation' => 'Operator and: True and False = False (keduanya harus True).',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi logika berikut?',
                'code_snippet' => 'print(True or False)',
                'options' => json_encode(['True', 'False', 'Error', 'None']),
                'correct_answer' => 'True',
                'explanation' => 'Operator or: True or False = True (salah satu True sudah cukup).',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah operator perbandingan "sama dengan" di Python?',
                'code_snippet' => null,
                'options' => json_encode(['==', '=', '!=', '===']),
                'correct_answer' => '==',
                'explanation' => 'Gunakan == untuk membandingkan apakah dua nilai sama. (= adalah assignment).',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa fungsi dari operator += pada kode berikut?',
                'code_snippet' => 'x = 5 x += 3',
                'options' => json_encode(['x = x + 3', 'x = 3', 'x += 3 (syntax error)', 'x = 5 + 3']),
                'correct_answer' => 'x = x + 3',
                'explanation' => 'x += 3 adalah shortcut dari x = x + 3 (assignment operator).',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi berikut?',
                'code_snippet' => 'print(15 + 5 * 2)',
                'options' => json_encode(['25', '40', '100', '20']),
                'correct_answer' => '25',
                'explanation' => 'Perkalian didahulukan: 5 * 2 = 10, lalu 15 + 10 = 25.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah operator NOT (negasi) di Python?',
                'code_snippet' => null,
                'options' => json_encode(['not', '!', '~', 'no']),
                'correct_answer' => 'not',
                'explanation' => 'Python menggunakan keyword not untuk negasi boolean, bukan tanda !.',
                'test_cases' => null,
            ],
        ];

        $level4Questions = [
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'kata = "Python" print(kata[0])',
                'options' => json_encode(['P', 'y', '0', 'Error']),
                'correct_answer' => 'P',
                'explanation' => 'Index 0 mengambil karakter pertama dari string, yaitu "P".',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'kata = "Python" print(kata[-1])',
                'options' => json_encode(['n', 'P', 'h', 'Error']),
                'correct_answer' => 'n',
                'explanation' => 'Index -1 mengambil karakter terakhir dari string, yaitu "n".',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'kata = "Python" print(kata[0:3])',
                'options' => json_encode(['Pyt', 'Pyth', 'yth', 'P']),
                'correct_answer' => 'Pyt',
                'explanation' => 'Slicing [0:3] mengambil karakter index 0 sampai 2 (sebelum index 3): "Pyt".',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print(len("Hello"))',
                'options' => json_encode(['5', '4', '6', 'Hello']),
                'correct_answer' => '5',
                'explanation' => 'Fungsi len() menghitung panjang string. "Hello" memiliki 5 karakter.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang digunakan untuk mengubah string menjadi huruf besar semua?',
                'code_snippet' => null,
                'options' => json_encode(['upper()', 'uppercase()', 'toUpper()', 'capitalize()']),
                'correct_answer' => 'upper()',
                'explanation' => 'Method upper() mengubah semua huruf dalam string menjadi kapital.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk menggabungkan string "Py" dan "thon"?',
                'code_snippet' => null,
                'options' => json_encode(['"Py" + "thon"', '"Py" . "thon"', '"Py" & "thon"', 'concat("Py", "thon")']),
                'correct_answer' => '"Py" + "thon"',
                'explanation' => 'Operator + digunakan untuk concatenation (penggabungan string) di Python.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar menggunakan f-string di Python?',
                'code_snippet' => null,
                'options' => json_encode([
                    'f"Nama saya {nama}"',
                    '"Nama saya {nama}"',
                    'f"Nama saya nama"',
                    'format("Nama saya {nama}")'
                ]),
                'correct_answer' => 'f"Nama saya {nama}"',
                'explanation' => 'f-string menggunakan prefix f dan kurung kurawal {} untuk menyisipkan variabel.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print("  Halo  ".strip())',
                'options' => json_encode(['Halo', '  Halo  ', 'Halo  ', '  Halo']),
                'correct_answer' => 'Halo',
                'explanation' => 'Method strip() menghapus spasi di awal dan akhir string.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apakah yang digunakan untuk memecah string menjadi list berdasarkan pemisah?',
                'code_snippet' => null,
                'options' => json_encode(['split()', 'break()', 'divide()', 'separate()']),
                'correct_answer' => 'split()',
                'explanation' => 'Method split() memecah string menjadi list berdasarkan delimiter (default spasi).',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print("Py" * 3)',
                'options' => json_encode(['PyPyPy', 'Py3', 'Py Py Py', 'Error']),
                'correct_answer' => 'PyPyPy',
                'explanation' => 'Operator * pada string mengulang string sebanyak n kali.',
                'test_cases' => null,
            ],
        ];

        $level5Questions = [
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk membuat list di Python?',
                'code_snippet' => null,
                'options' => json_encode(['[1, 2, 3]', '(1, 2, 3)', '{1, 2, 3}', '<1, 2, 3>']),
                'correct_answer' => '[1, 2, 3]',
                'explanation' => 'List dibuat menggunakan tanda kurung siku [].',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'buah = ["apel", "pisang", "jeruk"] print(buah[1])',
                'options' => json_encode(['pisang', 'apel', 'jeruk', '1']),
                'correct_answer' => 'pisang',
                'explanation' => 'Index 1 mengambil elemen kedua dari list (dimulai dari 0).',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang digunakan untuk menambah elemen ke akhir list?',
                'code_snippet' => null,
                'options' => json_encode(['append()', 'add()', 'push()', 'insert()']),
                'correct_answer' => 'append()',
                'explanation' => 'append() menambahkan satu elemen ke posisi terakhir list.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'angka = [3, 1, 2] angka.sort() print(angka)',
                'options' => json_encode(['[1, 2, 3]', '[3, 2, 1]', '[3, 1, 2]', 'Error']),
                'correct_answer' => '[1, 2, 3]',
                'explanation' => 'Method sort() mengurutkan list secara ascending (dari kecil ke besar).',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'a = [1, 2, 3] b = a[0:2] print(b)',
                'options' => json_encode(['[1, 2]', '[1, 2, 3]', '[2, 3]', '[1]']),
                'correct_answer' => '[1, 2]',
                'explanation' => 'Slicing [0:2] mengambil elemen index 0 dan 1 (sebelum index 2).',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara menghapus elemen terakhir dari list?',
                'code_snippet' => null,
                'options' => json_encode(['pop()', 'remove()', 'delete()', 'hapus()']),
                'correct_answer' => 'pop()',
                'explanation' => 'pop() tanpa argumen menghapus dan mengembalikan elemen terakhir list.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah list comprehension yang benar untuk membuat list [0, 2, 4, 6, 8]?',
                'code_snippet' => null,
                'options' => json_encode([
                    '[x for x in range(10) if x % 2 == 0]',
                    '[x for x in range(0, 10, 2)]',
                    'Semua benar',
                    '[x*2 for x in range(5)]'
                ]),
                'correct_answer' => 'Semua benar',
                'explanation' => 'Ketiga cara tersebut menghasilkan list [0, 2, 4, 6, 8].',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara mengakses elemen baris 1 kolom 2 dari matrix berikut?',
                'code_snippet' => 'matrix = [[1, 2], [3, 4]]',
                'options' => json_encode(['matrix[1][1]', 'matrix[1][2]', 'matrix[0][1]', 'matrix[2][2]']),
                'correct_answer' => 'matrix[1][1]',
                'explanation' => 'Baris 1 (index 1) = [3, 4], Kolom 2 (index 1) = 4. Jadi matrix[1][1] = 4.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'list_a = [1, 2] list_b = [3, 4] print(list_a + list_b)',
                'options' => json_encode(['[1, 2, 3, 4]', '[4, 6]', '[1, 2, 3, 4]', 'Error']),
                'correct_answer' => '[1, 2, 3, 4]',
                'explanation' => 'Operator + pada list menggabungkan (concatenate) dua list.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa panjang list setelah kode berikut dijalankan?',
                'code_snippet' => 'x = [1, 2, 3] x.append(4) x.pop() print(len(x))',
                'options' => json_encode(['3', '4', '2', '5']),
                'correct_answer' => '3',
                'explanation' => 'append(4) menambah jadi [1,2,3,4], lalu pop() menghapus elemen terakhir, kembali ke [1,2,3]. Panjangnya 3.',
                'test_cases' => null,
            ],
        ];

        $level6Questions = [
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk membuat tuple?',
                'code_snippet' => null,
                'options' => json_encode(['(1, 2, 3)', '[1, 2, 3]', '{1, 2, 3}', '<1, 2, 3>']),
                'correct_answer' => '(1, 2, 3)',
                'explanation' => 'Tuple dibuat menggunakan tanda kurung biasa ().',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa karakteristik utama dari tuple dibandingkan list?',
                'code_snippet' => null,
                'options' => json_encode(['Immutable (tidak bisa diubah)', 'Mutable (bisa diubah)', 'Hanya bisa berisi angka', 'Tidak bisa diakses indexnya']),
                'correct_answer' => 'Immutable (tidak bisa diubah)',
                'explanation' => 'Tuple bersifat immutable, artinya elemennya tidak bisa diubah setelah dibuat.',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'debugging',
                'answer_type' => 'mcq',
                'question_text' => 'Mengapa kode berikut error?',
                'code_snippet' => 'warna = ("merah", "hijau", "biru") warna[1] = "kuning"',
                'options' => json_encode([
                    'Tuple tidak bisa diubah (immutable)',
                    'Sintaks assignment salah',
                    'Index 1 tidak ada',
                    'Tuple hanya bisa sekali diisi'
                ]),
                'correct_answer' => 'Tuple tidak bisa diubah (immutable)',
                'explanation' => 'Tuple bersifat immutable, sehingga tidak bisa diubah elemennya setelah dibuat.',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'a, b, c = (10, 20, 30) print(a, b, c)',
                'options' => json_encode(['10 20 30', '(10, 20, 30)', 'Error', '10']),
                'correct_answer' => '10 20 30',
                'explanation' => 'Tuple unpacking: setiap variabel mendapat nilai dari elemen tuple sesuai urutan.',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara membuat set di Python?',
                'code_snippet' => null,
                'options' => json_encode(['{1, 2, 3}', '[1, 2, 3]', '(1, 2, 3)', 'set(1, 2, 3)']),
                'correct_answer' => '{1, 2, 3}',
                'explanation' => 'Set dibuat menggunakan tanda kurung kurawal {} atau fungsi set().',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'buah = {"apel", "pisang", "apel", "jeruk"} print(buah)',
                'options' => json_encode(['{"apel", "pisang", "jeruk"}', '{"apel", "pisang", "apel", "jeruk"}', 'Error', '["apel", "pisang", "jeruk"]']),
                'correct_answer' => '{"apel", "pisang", "jeruk"}',
                'explanation' => 'Set tidak mengizinkan duplikat, jadi "apel" yang kedua otomatis dihapus.',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa untuk menambah elemen ke set?',
                'code_snippet' => null,
                'options' => json_encode(['add()', 'append()', 'insert()', 'push()']),
                'correct_answer' => 'add()',
                'explanation' => 'Set menggunakan method add() untuk menambah elemen (bukan append()).',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Operator apa yang digunakan untuk union (gabungan) dua set?',
                'code_snippet' => null,
                'options' => json_encode(['|', '&', '-', '^']),
                'correct_answer' => '|',
                'explanation' => 'Operator | digunakan untuk union (gabungan semua elemen dari kedua set).',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Operator apa untuk intersection (irisan) dua set?',
                'code_snippet' => null,
                'options' => json_encode(['&', '|', '-', '^']),
                'correct_answer' => '&',
                'explanation' => 'Operator & digunakan untuk intersection (elemen yang ada di kedua set).',
                'test_cases' => null,
            ],
            [
                'level_id' => 6,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah yang bisa dijadikan key di dictionary?',
                'code_snippet' => null,
                'options' => json_encode(['Tuple', 'List', 'Set', 'Dictionary']),
                'correct_answer' => 'Tuple',
                'explanation' => 'Tuple (immutable) bisa jadi key dictionary, sedangkan list/set/dict (mutable) tidak bisa.',
                'test_cases' => null,
            ],
        ];

        $level7Questions = [
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara yang benar untuk membuat dictionary?',
                'code_snippet' => null,
                'options' => json_encode(['{"nama": "Budi", "umur": 17}', '["nama": "Budi", "umur": 17]', '("nama": "Budi", "umur": 17)', '<"nama": "Budi", "umur": 17>']),
                'correct_answer' => '{"nama": "Budi", "umur": 17}',
                'explanation' => 'Dictionary dibuat dengan kurung kurawal {} berisi pasangan key: value.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara mengakses nilai dari key "nama" dalam dictionary?',
                'code_snippet' => 'siswa = {"nama": "Budi", "umur": 17}',
                'options' => json_encode(['siswa["nama"]', 'siswa.nama', 'siswa->nama', 'siswa("nama")']),
                'correct_answer' => 'siswa["nama"]',
                'explanation' => 'Akses nilai dictionary menggunakan kurung siku dengan key: dict["key"].',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang mengembalikan semua key dalam dictionary?',
                'code_snippet' => null,
                'options' => json_encode(['keys()', 'getkeys()', 'allkeys()', 'keylist()']),
                'correct_answer' => 'keys()',
                'explanation' => 'Method keys() mengembalikan semua key dalam dictionary.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang mengembalikan semua value dalam dictionary?',
                'code_snippet' => null,
                'options' => json_encode(['values()', 'getvalues()', 'allvalues()', 'valuelist()']),
                'correct_answer' => 'values()',
                'explanation' => 'Method values() mengembalikan semua nilai dalam dictionary.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'siswa = {"nama": "Budi", "umur": 17} print(siswa.get("alamat", "tidak ada"))',
                'options' => json_encode(['tidak ada', 'None', 'Error', 'alamat']),
                'correct_answer' => 'tidak ada',
                'explanation' => 'Method get() mengembalikan default value jika key tidak ditemukan.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Bagaimana cara menambah key-value baru ke dictionary?',
                'code_snippet' => 'siswa = {"nama": "Budi"}',
                'options' => json_encode([
                    'siswa["umur"] = 17',
                    'siswa.add("umur", 17)',
                    'siswa.push("umur", 17)',
                    'siswa.insert("umur", 17)'
                ]),
                'correct_answer' => 'siswa["umur"] = 17',
                'explanation' => 'Assign nilai ke key baru: dict["key_baru"] = nilai.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'data = {"a": 1, "b": 2} print(len(data))',
                'options' => json_encode(['2', '1', '4', 'Error']),
                'correct_answer' => '2',
                'explanation' => 'Fungsi len() pada dictionary mengembalikan jumlah pasangan key-value.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang menghapus item berdasarkan key dan mengembalikan nilainya?',
                'code_snippet' => null,
                'options' => json_encode(['pop()', 'remove()', 'delete()', 'hapus()']),
                'correct_answer' => 'pop()',
                'explanation' => 'pop(key) menghapus item berdasarkan key dan mengembalikan nilainya.',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'sekolah = {"siswa1": {"nama": "Budi", "nilai": 90}} print(sekolah["siswa1"]["nama"])',
                'options' => json_encode(['Budi', 'siswa1', '90', 'Error']),
                'correct_answer' => 'Budi',
                'explanation' => 'Nested dictionary diakses dengan rantai key: dict[outer_key][inner_key].',
                'test_cases' => null,
            ],
            [
                'level_id' => 7,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Method apa yang mengembalikan semua pasangan key-value sebagai tuple?',
                'code_snippet' => null,
                'options' => json_encode(['items()', 'pairs()', 'entries()', 'tuples()']),
                'correct_answer' => 'items()',
                'explanation' => 'items() mengembalikan semua pasangan (key, value) dalam bentuk tuple.',
                'test_cases' => null,
            ],
        ];

        $level8Questions = [
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah struktur if yang benar di Python?',
                'code_snippet' => null,
                'options' => json_encode([
                    'if x > 5: print("Besar")',
                    'if (x > 5) { print("Besar") }',
                    'if x > 5 then print("Besar")',
                    'if x > 5: print("Besar")'
                ]),
                'correct_answer' => 'if x > 5: print("Besar")',
                'explanation' => 'Python menggunakan titik dua (:) dan indentasi untuk blok if.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'nilai = 75 if nilai >= 90: print("A") elif nilai >= 80: print("B") elif nilai >= 70: print("C") else: print("D")',
                'options' => json_encode(['C', 'B', 'A', 'D']),
                'correct_answer' => 'C',
                'explanation' => 'Nilai 75 memenuhi kondisi elif >= 70, jadi mencetak "C".',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Keyword apa untuk "else if" di Python?',
                'code_snippet' => null,
                'options' => json_encode(['elif', 'elseif', 'else if', 'elsif']),
                'correct_answer' => 'elif',
                'explanation' => 'Python menggunakan keyword elif untuk kondisi tambahan (else if).',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'x = 10 if x > 5: if x > 8: print("A") else: print("B")',
                'options' => json_encode(['A', 'B', 'A B', 'Tidak ada output']),
                'correct_answer' => 'A',
                'explanation' => 'x=10 > 5 (True) dan x=10 > 8 (True), jadi nested if mencetak "A".',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah operator logika AND di Python?',
                'code_snippet' => null,
                'options' => json_encode(['and', '&&', '&', 'and then']),
                'correct_answer' => 'and',
                'explanation' => 'Python menggunakan keyword and untuk logika AND, bukan &&.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'print(5 > 3 and 2 < 1)',
                'options' => json_encode(['False', 'True', 'Error', 'None']),
                'correct_answer' => 'False',
                'explanation' => '5 > 3 = True, 2 < 1 = False. True and False = False.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah penulisan ternary operator yang benar di Python?',
                'code_snippet' => null,
                'options' => json_encode([
                    '"Dewasa" if umur >= 17 else "Anak-anak"',
                    'umur >= 17 ? "Dewasa" : "Anak-anak"',
                    'if umur >= 17 then "Dewasa" else "Anak-anak"',
                    '"Dewasa" ? umur >= 17 : "Anak-anak"'
                ]),
                'correct_answer' => '"Dewasa" if umur >= 17 else "Anak-anak"',
                'explanation' => 'Ternary Python: nilai_jika_true if kondisi else nilai_jika_false.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Operator apa untuk mengecek apakah suatu nilai ada dalam list?',
                'code_snippet' => null,
                'options' => json_encode(['in', 'contains', 'has', 'exists']),
                'correct_answer' => 'in',
                'explanation' => 'Operator in mengecek membership: "apel" in ["apel", "pisang"] menghasilkan True.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa fungsi dari keyword pass di Python?',
                'code_snippet' => null,
                'options' => json_encode(['Tidak melakukan apa-apa (placeholder)', 'Melewati iterasi loop', 'Menghentikan program', 'Melanjutkan ke baris berikutnya']),
                'correct_answer' => 'Tidak melakukan apa-apa (placeholder)',
                'explanation' => 'pass adalah perintah kosong yang tidak melakukan apa-apa, digunakan sebagai placeholder.',
                'test_cases' => null,
            ],
            [
                'level_id' => 8,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'a = [1, 2, 3] b = [1, 2, 3] print(a == b)',
                'options' => json_encode(['True', 'False', 'Error', 'None']),
                'correct_answer' => 'True',
                'explanation' => 'Operator == membandingkan nilai/isi, bukan objek. a dan b memiliki isi yang sama.',
                'test_cases' => null,
            ],
        ];

        $level9Questions = [
            [
                'level_id' => 9,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah kode for loop yang benar untuk mencetak angka 1 sampai 5?',
                'code_snippet' => null,
                'options' => json_encode([
                    'for i in range(1, 6): print(i)',
                    'for i in range(1, 5): print(i)',
                    'for i in range(5): print(i)',
                    'for (i=1; i<=5; i++): print(i)'
                ]),
                'correct_answer' => 'for i in range(1, 6): print(i)',
                'explanation' => 'range(1, 6) menghasilkan angka 1, 2, 3, 4, 5 (stop value tidak termasuk).',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa kali blok for berikut akan dijalankan?',
                'code_snippet' => 'for i in range(3): print("Halo")',
                'options' => json_encode(['3', '2', '4', '1']),
                'correct_answer' => '3',
                'explanation' => 'range(3) menghasilkan 0, 1, 2 - total 3 iterasi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah struktur while loop yang benar?',
                'code_snippet' => null,
                'options' => json_encode([
                    'i = 0 while i < 5: print(i) i += 1',
                    'while i < 5: print(i) i++',
                    'i = 0 while i < 5: print(i)',
                    'while (i < 5) { print(i) i++ }'
                ]),
                'correct_answer' => 'i = 0 while i < 5: print(i) i += 1',
                'explanation' => 'While loop perlu inisialisasi, kondisi, dan increment manual. Python tidak punya i++.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'for i in range(5): if i == 3: break print(i)',
                'options' => json_encode(['0 1 2', '0 1 2 3', '0 1 2 3 4', '3']),
                'correct_answer' => '0 1 2',
                'explanation' => 'Break menghentikan loop saat i == 3, jadi yang tercetak hanya 0, 1, 2.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'for i in range(5): if i == 2: continue print(i)',
                'options' => json_encode(['0 1 3 4', '0 1 2 3 4', '0 1 2', '2']),
                'correct_answer' => '0 1 3 4',
                'explanation' => 'continue melewati iterasi saat i == 2, jadi angka 2 tidak dicetak.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Range apa yang menghasilkan angka 0, 2, 4, 6, 8?',
                'code_snippet' => null,
                'options' => json_encode(['range(0, 10, 2)', 'range(0, 9, 2)', 'range(2, 10, 2)', 'range(0, 8, 2)']),
                'correct_answer' => 'range(0, 10, 2)',
                'explanation' => 'range(start, stop, step): 0, 2, 4, 6, 8 (stop 10 tidak termasuk).',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'buah = ["apel", "mangga"] for i, b in enumerate(buah): print(i, b)',
                'options' => json_encode(['0 apel 1 mangga', 'apel mangga', '1 apel 2 mangga', '0 apel 1 mangga']),
                'correct_answer' => '0 apel 1 mangga',
                'explanation' => 'enumerate() memberikan index (mulai dari 0) dan nilai dari setiap elemen.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa total iterasi dari nested loop berikut?',
                'code_snippet' => 'for i in range(3): for j in range(2): print(i, j)',
                'options' => json_encode(['6', '3', '2', '5']),
                'correct_answer' => '6',
                'explanation' => 'Loop luar 3 kali, loop dalam 2 kali: 3 x 2 = 6 total iterasi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Kapan blok else pada for loop dijalankan?',
                'code_snippet' => null,
                'options' => json_encode([
                    'Jika loop selesai tanpa break',
                    'Jika loop gagal',
                    'Setiap kali loop selesai',
                    'Jika ada error'
                ]),
                'correct_answer' => 'Jika loop selesai tanpa break',
                'explanation' => 'Blok else pada loop dieksekusi jika loop berakhir normal (tanpa break).',
                'test_cases' => null,
            ],
            [
                'level_id' => 9,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Manakah cara membuat infinite loop yang benar?',
                'code_snippet' => null,
                'options' => json_encode(['while True:', 'for (;;):', 'loop:', 'while 1:']),
                'correct_answer' => 'while True:',
                'explanation' => 'while True: akan berjalan terus karena kondisi selalu True. (while 1: juga valid).',
                'test_cases' => null,
            ],
        ];

        $level10Questions = [
            [
                'level_id' => 10,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Keyword apa yang digunakan untuk mendefinisikan fungsi?',
                'code_snippet' => null,
                'options' => json_encode(['def', 'function', 'func', 'define']),
                'correct_answer' => 'def',
                'explanation' => 'Fungsi didefinisikan dengan keyword def diikuti nama fungsi dan parameter.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'def tambah(a, b): return a + b hasil = tambah(5, 3) print(hasil)',
                'options' => json_encode(['8', '53', '5 + 3', 'Error']),
                'correct_answer' => '8',
                'explanation' => 'Fungsi tambah(5, 3) mengembalikan 5 + 3 = 8.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari fungsi dengan default parameter?',
                'code_snippet' => 'def sapa(nama="Teman"): print(f"Halo, {nama}!") sapa()',
                'options' => json_encode(['Halo, Teman!', 'Halo, !', 'Error', 'Halo, nama!']),
                'correct_answer' => 'Halo, Teman!',
                'explanation' => 'Parameter nama memiliki default "Teman", jadi sapa() menggunakan nilai default.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'def hitung(a, b): return a + b, a - b x, y = hitung(10, 3) print(x, y)',
                'options' => json_encode(['13 7', '7 13', '(13, 7)', 'Error']),
                'correct_answer' => '13 7',
                'explanation' => 'Fungsi mengembalikan tuple (a+b, a-b) = (13, 7), lalu di-unpack ke x dan y.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'x = 10 def ubah(): x = 20 ubah() print(x)',
                'options' => json_encode(['10', '20', 'Error', 'None']),
                'correct_answer' => '10',
                'explanation' => 'x = 20 di dalam fungsi adalah variabel lokal, tidak mengubah x global. Jadi x tetap 10.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Cara yang benar untuk membuat fungsi lambda yang mengkuadratkan angka?',
                'code_snippet' => null,
                'options' => json_encode([
                    'kuadrat = lambda x: x ** 2',
                    'kuadrat = lambda x { x ** 2 }',
                    'lambda(x): x ** 2',
                    'def lambda(x): return x ** 2'
                ]),
                'correct_answer' => 'kuadrat = lambda x: x ** 2',
                'explanation' => 'Lambda ditulis: lambda parameter: ekspresi. Tanpa keyword return.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa fungsi dari *args pada parameter fungsi?',
                'code_snippet' => null,
                'options' => json_encode([
                    'Menerima jumlah argumen posisi tak terbatas',
                    'Menerima argumen keyword tak terbatas',
                    'Menandai argumen wajib',
                    'Memberi nilai default'
                ]),
                'correct_answer' => 'Menerima jumlah argumen posisi tak terbatas',
                'explanation' => '*args mengumpulkan semua argumen posisi tambahan ke dalam tuple.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa fungsi dari **kwargs pada parameter fungsi?',
                'code_snippet' => null,
                'options' => json_encode([
                    'Menerima argumen keyword tak terbatas',
                    'Menerima argumen posisi tak terbatas',
                    'Menandai argumen opsional',
                    'Mendefinisikan keyword function'
                ]),
                'correct_answer' => 'Menerima argumen keyword tak terbatas',
                'explanation' => '**kwargs mengumpulkan semua argumen keyword tambahan ke dalam dictionary.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'def total(*args): return sum(args) print(total(1, 2, 3, 4))',
                'options' => json_encode(['10', '1 2 3 4', 'Error', '6']),
                'correct_answer' => '10',
                'explanation' => '*args mengumpulkan 1,2,3,4 menjadi tuple, lalu sum() menjumlahkannya = 10.',
                'test_cases' => null,
            ],
            [
                'level_id' => 10,
                'type' => 'coding',
                'answer_type' => 'mcq',
                'question_text' => 'Apa yang dikembalikan fungsi jika tidak ada keyword return?',
                'code_snippet' => null,
                'options' => json_encode(['None', '0', 'Error', 'False']),
                'correct_answer' => 'None',
                'explanation' => 'Fungsi tanpa return mengembalikan None secara implisit.',
                'test_cases' => null,
            ],
        ];

        foreach ($level1Questions as $q) DB::table('questions')->insert($q);
        foreach ($level2Questions as $q) DB::table('questions')->insert($q);
        foreach ($level3Questions as $q) DB::table('questions')->insert($q);
        foreach ($level4Questions as $q) DB::table('questions')->insert($q);
        foreach ($level5Questions as $q) DB::table('questions')->insert($q);
        foreach ($level6Questions as $q) DB::table('questions')->insert($q);
        foreach ($level7Questions as $q) DB::table('questions')->insert($q);
        foreach ($level8Questions as $q) DB::table('questions')->insert($q);
        foreach ($level9Questions as $q) DB::table('questions')->insert($q);
        foreach ($level10Questions as $q) DB::table('questions')->insert($q);
    }
}
