<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder
{
    public function run(): void
    {
        // Level 1 - Dasar Python
        $level1Questions = [
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari perintah print("Hello World")?',
                'code_snippet' => 'print("Hello World")',
                'options' => json_encode(['Hello World', 'hello world', 'HELLO WORLD', 'Tidak ada output']),
                'correct_answer' => 'Hello World',
                'explanation' => 'Fungsi print() akan menampilkan teks yang diapit tanda kutip apa adanya.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buatlah variabel bernama "nama" dengan nilai "PyLearn" lalu cetak nilainya.',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'nama = "PyLearn"\nprint(nama)',
                'explanation' => 'Variabel dibuat dengan syntax: nama_variabel = nilai. Kemudian dicetak dengan print().',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa tipe data dari nilai 3.14?',
                'code_snippet' => 'x = 3.14',
                'options' => json_encode(['int', 'float', 'str', 'bool']),
                'correct_answer' => 'float',
                'explanation' => 'Angka desimal (dengan titik) dalam Python bertipe float.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Hitung dan cetak hasil dari 15 + 25 * 3',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'print(15 + 25 * 3)',
                'explanation' => 'Dalam operasi matematika, perkalian (*) dilakukan lebih dulu, lalu penjumlahan. Jadi 25 * 3 = 75, lalu 15 + 75 = 90.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari operasi berikut?',
                'code_snippet' => 'print(10 // 3)',
                'options' => json_encode(['3.33', '3', '4', 'Error']),
                'correct_answer' => '3',
                'explanation' => 'Operator // adalah floor division (pembagian bulat ke bawah). 10 // 3 = 3.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'debugging',
                'answer_type' => 'essay',
                'question_text' => 'Perbaiki kode berikut agar tidak error: print "Hello"',
                'code_snippet' => 'print "Hello"',
                'options' => null,
                'correct_answer' => 'print("Hello")',
                'explanation' => 'Di Python 3, print adalah fungsi sehingga harus menggunakan tanda kurung.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari len("Python")?',
                'code_snippet' => 'len("Python")',
                'options' => json_encode(['6', '5', '7', 'Error']),
                'correct_answer' => '6',
                'explanation' => 'Fungsi len() menghitung jumlah karakter dalam string. "Python" memiliki 6 huruf.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat tiga variabel: a = 5, b = 3, lalu cetak hasil a - b',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'a = 5\nb = 3\nprint(a - b)',
                'explanation' => 'Variabel dapat dikurangkan satu sama lain dengan operasi -',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa tipe data dari boolean True?',
                'code_snippet' => 'x = True',
                'options' => json_encode(['int', 'str', 'bool', 'float']),
                'correct_answer' => 'bool',
                'explanation' => 'True dan False adalah tipe data boolean di Python.',
                'test_cases' => null,
            ],
            [
                'level_id' => 1,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat variabel berisi nama ciudad favoritmu dan cetak dengan format: "Ciudad favorita: [nama]"',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'ciudad = "Tokyo"\nprint(f"Ciudad favorita: {ciudad}")',
                'explanation' => 'String interpolation dapat menggunakan f-string atau concatenation.',
                'test_cases' => null,
            ],
        ];

        // Level 2 - Percabangan
        $level2Questions = [
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat kode jika usia >= 18 cetak "Dewasa"',
                'code_snippet' => 'usia = 20',
                'options' => null,
                'correct_answer' => 'usia = 20\nif usia >= 18:\n    print("Dewasa")',
                'explanation' => 'Gunakan if statement dengan kondisi >= 18.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari kode berikut?',
                'code_snippet' => 'x = 5\nif x > 3:\n    print("A")\nelse:\n    print("B")',
                'options' => json_encode(['A', 'B', 'A B', 'Error']),
                'correct_answer' => 'A',
                'explanation' => 'Karena 5 > 3 bernilai True, maka blok if akan dieksekusi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat kondisi if-else untuk memeriksa apakah angka adalah genap atau ganjil',
                'code_snippet' => 'angka = 7',
                'options' => null,
                'correct_answer' => 'angka = 7\nif angka % 2 == 0:\n    print("Genap")\nelse:\n    print("Ganjil")',
                'explanation' => 'Gunakan operator modulo (%) untuk menentukan sisa bagi. Jika sisa 0 berarti genap.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari nested if berikut?',
                'code_snippet' => 'x = 10\nif x > 5:\n    if x > 8:\n        print("A")\n    else:\n        print("B")',
                'options' => json_encode(['A', 'B', 'A dan B', 'Tidak ada output']),
                'correct_answer' => 'A',
                'explanation' => 'x=10 > 5 (True) dan x=10 > 8 (True), jadi print("A")',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat program login sederhana: jika username="admin" dan password="123" print "Login berhasil" selain itu print "Login gagal"',
                'code_snippet' => 'username = "admin"\npassword = "123"',
                'options' => null,
                'correct_answer' => 'username = "admin"\npassword = "123"\nif username == "admin" and password == "123":\n    print("Login berhasil")\nelse:\n    print("Login gagal")',
                'explanation' => 'Gunakan operator logika AND untuk menggabungkan dua kondisi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari elif berikut?',
                'code_snippet' => 'nilai = 75\nif nilai >= 90:\n    print("A")\nelif nilai >= 80:\n    print("B")\nelif nilai >= 70:\n    print("C")\nelse:\n    print("D")',
                'options' => json_encode(['A', 'B', 'C', 'D']),
                'correct_answer' => 'C',
                'explanation' => 'Nilai 75 memenuhi kondisi >= 70 pada elif ketiga, jadi print "C".',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'debugging',
                'answer_type' => 'essay',
                'question_text' => 'Perbaiki syntax error pada kode berikut: if x > 5 print("Besar")',
                'code_snippet' => 'if x > 5 print("Besar")',
                'options' => null,
                'correct_answer' => 'x = 6\nif x > 5:\n    print("Besar")',
                'explanation' => 'Setelah kondisi if harus ada tanda titik dua (:) dan blok kode harus diindent.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat program untuk menentukan grade: >= 90 A, >= 80 B, >= 70 C, selain itu D',
                'code_snippet' => 'nilai = 85',
                'options' => null,
                'correct_answer' => 'nilai = 85\nif nilai >= 90:\n    print("A")\nelif nilai >= 80:\n    print("B")\nelif nilai >= 70:\n    print("C")\nelse:\n    print("D")',
                'explanation' => 'Gunakan elif untuk membuat rentang nilai berjenjang.',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa hasil dari operasi boolean?',
                'code_snippet' => 'print(True and False or True)',
                'options' => json_encode(['True', 'False', 'Error', 'None']),
                'correct_answer' => 'True',
                'explanation' => 'True and False = False, lalu False or True = True (short-circuit evaluation).',
                'test_cases' => null,
            ],
            [
                'level_id' => 2,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat kondisi untuk menentukan apakah seseorang boleh memilih: usia >= 17 dan punya KTP',
                'code_snippet' => 'usia = 20\npunya_ktp = True',
                'options' => null,
                'correct_answer' => 'usia = 20\npunya_ktp = True\nif usia >= 17 and punya_ktp:\n    print("Boleh memilih")\nelse:\n    print("Tidak boleh memilih")',
                'explanation' => 'Gunakan AND untuk kedua kondisi harus terpenuhi.',
                'test_cases' => null,
            ],
        ];

        // Level 3 - Looping
        $level3Questions = [
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat loop for untuk menampilkan angka 1 sampai 5',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(1, 6):\n    print(i)',
                'explanation' => 'range(1, 6) menghasilkan 1,2,3,4,5. Penggunaan range(start, end+1).',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa kali loop ini akan berjalan?',
                'code_snippet' => 'for i in range(3):\n    print(i)',
                'options' => json_encode(['2', '3', '4', 'Tidak terbatas']),
                'correct_answer' => '3',
                'explanation' => 'range(3) menghasilkan 0, 1, 2 - total 3 iterasi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat while loop yang menghitung dari 0 sampai 4',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'i = 0\nwhile i < 5:\n    print(i)\n    i += 1',
                'explanation' => 'While loop berjalan selama kondisi True, perlu increment untuk menghindari infinite loop.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari break dalam loop?',
                'code_snippet' => 'for i in range(5):\n    if i == 3:\n        break\n    print(i)',
                'options' => json_encode(['0 1 2', '0 1 2 3', '3', '0 1 2 3 4']),
                'correct_answer' => '0 1 2',
                'explanation' => 'Break menghentikan loop saat i mencapai 3, jadi 0,1,2 dicetak.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat for loop untuk menghitung total bilangan genap dari 1 sampai 10',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'total = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        total += i\nprint(total)',
                'explanation' => 'Gunakan modulo untuk mendeteksi bilangan genap, lalu tambahkan ke total.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa fungsi continue dalam loop?',
                'code_snippet' => 'for i in range(3):\n    if i == 1:\n        continue\n    print(i)',
                'options' => json_encode(['Menghentikan loop', 'Melanjutkan ke iterasi berikutnya', 'Mengulang iterasi saat ini', 'Tidak ada efek']),
                'correct_answer' => 'Melanjutkan ke iterasi berikutnya',
                'explanation' => 'Continue melewati sisa kode dalam iterasi dan langsung ke iterasi berikutnya.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat loop untuk menampilkan bilangan kelipatan 3 dari 3 sampai 15',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(3, 16, 3):\n    print(i)',
                'explanation' => 'Gunakan range(start, end, step) dengan step 3.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa total penjumlahan dari 1+2+3+4+5?',
                'code_snippet' => 'total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)',
                'options' => json_encode(['10', '15', '20', '25']),
                'correct_answer' => '15',
                'explanation' => '1+2+3+4+5 = 15',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat program untuk mencari bilangan pertama yang habis dibagi 7 antara 1-30',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(1, 31):\n    if i % 7 == 0:\n        print(i)\n        break',
                'explanation' => 'Gunakan break untuk berhenti saat menemukan bilangan pertama.',
                'test_cases' => null,
            ],
            [
                'level_id' => 3,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat while loop yang berhenti saat mencapai angka 5',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'i = 1\nwhile True:\n    print(i)\n    if i == 5:\n        break\n    i += 1',
                'explanation' => 'Gunakan infinite loop dengan kondisi break untuk menghentikannya.',
                'test_cases' => null,
            ],
        ];

        // Level 4 - Looping Lanjutan
        $level4Questions = [
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat nested loop untuk menampilkan perkalian 1x1 sampai 3x3',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(1, 4):\n    for j in range(1, 4):\n        print(f"{i} x {j} = {i*j}")',
                'explanation' => 'Nested loop menggunakan dua variabel untuk membuat tabel perkalian.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Berapa total iterasi dari nested loop berikut?',
                'code_snippet' => 'for i in range(3):\n    for j in range(2):\n        pass',
                'options' => json_encode(['3', '2', '6', '5']),
                'correct_answer' => '6',
                'explanation' => '3 x 2 = 6 total iterasi.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat pola segitiga dengan menggunakan nested loop:\n*\n**\n***',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(1, 4):\n    print("*" * i)',
                'explanation' => 'Kalikan string dengan jumlah bintang per baris.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat loop untuk menghitung total elemen dalam list 2D',
                'code_snippet' => 'matrix = [[1,2], [3,4], [5,6]]',
                'options' => null,
                'correct_answer' => 'matrix = [[1,2], [3,4], [5,6]]\ntotal = 0\nfor row in matrix:\n    for item in row:\n        total += item\nprint(total)',
                'explanation' => 'Gunakan nested loop untuk mengakses setiap elemen dalam list 2D.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari enumerate berikut?',
                'code_snippet' => 'buah = ["apel", "mangga"]\nfor i, nama in enumerate(buah):\n    print(i, nama)',
                'options' => json_encode(['apel mangga', '0 apel 1 mangga', '1 apel 2 mangga', 'Error']),
                'correct_answer' => '0 apel 1 mangga',
                'explanation' => 'enumerate() mengembalikan index dan nilai dimulai dari 0.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Gunakan list comprehension untuk membuat list bilangan kuadrat 1-5',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'kuadrat = [x**2 for x in range(1, 6)]\nprint(kuadrat)',
                'explanation' => 'List comprehension adalah cara singkat membuat list dengan for dalam satu baris.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi untuk menampilkan bilangan prima dari 1-20',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for num in range(2, 21):\n    prima = True\n    for i in range(2, int(num**0.5) + 1):\n        if num % i == 0:\n            prima = False\n            break\n    if prima:\n        print(num)',
                'explanation' => 'Bilangan prima hanya habis dibagi 1 dan dirinya sendiri.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari zip dalam Python?',
                'code_snippet' => 'a = [1, 2, 3]\nb = ["a", "b", "c"]\nfor x, y in zip(a, b):\n    print(x, y)',
                'options' => json_encode(['1 a 2 b 3 c', 'a1 b2 c3', '1,2,3 a,b,c', 'Error']),
                'correct_answer' => '1 a 2 b 3 c',
                'explanation' => 'zip() menggabungkan elemen dari beberapa iterable berpasangan.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat pola piramida dengan tinggi 5',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'for i in range(1, 6):\n    print(" " * (5-i) + "*" * (2*i-1))',
                'explanation' => 'Gunakan spasi untuk rata tengah dan ganjil untuk jumlah bintang.',
                'test_cases' => null,
            ],
            [
                'level_id' => 4,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat program untuk menemukan semua faktor dari sebuah angka',
                'code_snippet' => 'angka = 12',
                'options' => null,
                'correct_answer' => 'angka = 12\nfaktor = []\nfor i in range(1, angka + 1):\n    if angka % i == 0:\n        faktor.append(i)\nprint(faktor)',
                'explanation' => 'Faktor adalah bilangan yang habis membagi angka tersebut.',
                'test_cases' => null,
            ],
        ];

        // Level 5 - Functions & Modules
        $level5Questions = [
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi bernama "salam" yang menerima nama dan menampilkan "Halo, [nama]!"',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'def salam(nama):\n    print(f"Halo, {nama}!")\n\nsalam("PyLearn")',
                'explanation' => 'Fungsi didefinisikan dengan keyword def, diikuti nama fungsi dan parameter.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari fungsi berikut?',
                'code_snippet' => 'def tambah(a, b=5):\n    return a + b\n\nprint(tambah(3))',
                'options' => json_encode(['3', '8', 'Error', 'None']),
                'correct_answer' => '8',
                'explanation' => 'Parameter b memiliki default value 5, jadi 3 + 5 = 8.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi untuk menghitung luas lingkaran dengan rumus π × r² (r=7)',
                'code_snippet' => 'import math',
                'options' => null,
                'correct_answer' => 'import math\n\ndef luas_lingkaran(r):\n    return math.pi * r ** 2\n\nprint(luas_lingkaran(7))',
                'explanation' => 'Gunakan math.pi untuk nilai π dan operator ** untuk pangkat.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi dengan return multiple values untuk mengembalikan hasil bagi dan sisa bagi',
                'code_snippet' => 'a = 17, b = 5',
                'options' => null,
                'correct_answer' => 'def bagi(a, b):\n    hasil = a // b\n    sisa = a % b\n    return hasil, sisa\n\nq, r = bagi(17, 5)\nprint(f"Hasil: {q}, Sisa: {r}")',
                'explanation' => 'Python dapat mengembalikan multiple values sebagai tuple.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa output dari *args?',
                'code_snippet' => 'def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3, 4))',
                'options' => json_encode(['10', '1 2 3 4', 'Error', 'None']),
                'correct_answer' => '10',
                'explanation' => '*args menerima jumlah argumen tak terbatas sebagai tuple.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi dengan kwargs untuk menerima data karyawan (nama, posisi, gaji)',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'def buat_karyawan(**kwargs):\n    for key, value in kwargs.items():\n        print(f"{key}: {value}")\n\nbuat_karyawan(nama="Budi", posisi="Developer", gaji=5000000)',
                'explanation' => '**kwargs menerima argumen keyword dalam bentuk dictionary.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Import modul math dan gunakan fungsi floor dan ceil untuk angka 4.7',
                'code_snippet' => 'import math',
                'options' => null,
                'correct_answer' => 'import math\nprint(math.floor(4.7))  # 4\nprint(math.ceil(4.7))   # 5',
                'explanation' => 'floor() membulatkan ke bawah, ceil() membulatkan ke atas.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'output',
                'answer_type' => 'mcq',
                'question_text' => 'Apa perbedaan antara return dan print?',
                'code_snippet' => 'def contoh():\n    return "hasil"\n\nprint(contoh())',
                'options' => json_encode(['Sama saja', 'return mengirim nilai, print menampilkan', 'return hanya untuk debugging', 'Tidak ada bedanya']),
                'correct_answer' => 'return mengirim nilai, print menampilkan',
                'explanation' => 'return menghasilkan nilai yang dapat digunakan lebih lanjut, print hanya menampilkan ke layar.',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat fungsi rekursif untuk menghitung faktorial dari 5',
                'code_snippet' => null,
                'options' => null,
                'correct_answer' => 'def faktorial(n):\n    if n == 0 or n == 1:\n        return 1\n    return n * faktorial(n-1)\n\nprint(faktorial(5))  # 120',
                'explanation' => 'Fungsi rekursif memanggil dirinya sendiri dengan kondisi berhenti (base case).',
                'test_cases' => null,
            ],
            [
                'level_id' => 5,
                'type' => 'coding',
                'answer_type' => 'essay',
                'question_text' => 'Buat module sederhana dengan fungsi untuk konversi Celsius ke Fahrenheit, lalu import dan gunakan',
                'code_snippet' => 'def celsius_ke_fahrenheit(c):\n    return (c * 9/5) + 32',
                'options' => null,
                'correct_answer' => '# module: konversi.py\ndef celsius_ke_fahrenheit(c):\n    return (c * 9/5) + 32\n\n# penggunaan\nfrom konversi import celsius_ke_fahrenheit\nprint(celsius_ke_fahrenheit(100))  # 212',
                'explanation' => 'Module adalah file Python yang dapat diimport untuk reuse kode.',
                'test_cases' => null,
            ],
        ];

        // Insert all questions
        $allQuestions = array_merge($level1Questions, $level2Questions, $level3Questions, $level4Questions, $level5Questions);
        
        foreach ($allQuestions as $question) {
            DB::table('questions')->insert($question);
        }
    }
}